### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schem a.

### ISSUE THREAD

**Issue by shawnnosaurus** [jsbonso/angular2-crudapp#1]
After installing all dependency packages, when I try to run the server, I get the following error:

![image](https://cloud.githubusercontent.com/assets/5610505/21838399/74db47aa-d7da-11e6-94ba-b57306dbc56c.png)

**Comment by calvinx408** [comment]
getting the same error

**Comment by amrinder-pal-singh** [comment]
@jsbonso  Please guide us on this error.

**Comment by ray040** [comment]
Not working after run npm start, throwing following exception:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2@0.0.0~prestart: angular2@0.0.0
6 silly lifecycle angular2@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2@0.0.0~start: angular2@0.0.0
8 verbose lifecycle angular2@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\ng\angular2-crudapp\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\PuTTY\;C:\Program Files\TortoiseSVN\bin;%M2_HOME%\bin;C:\Users\rayhanul.islam\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk1.8.0_112\bin;C:\sqlite\;C:\Program Files\nodejs\;C:\Users\rayhanul.islam\scoop\apps\ruby\current\gems\bin;C:\Users\rayhanul.islam\scoop\apps\ruby\current\bin;C:\Users\rayhanul.islam\scoop\shims;C:\Users\rayhanul.islam\AppData\Local\Microsoft\WindowsApps;C:\Users\rayhanul.islam\AppData\Roaming\npm
10 verbose lifecycle angular2@0.0.0~start: CWD: C:\ng\angular2-crudapp
11 silly lifecycle angular2@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
12 silly lifecycle angular2@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2@0.0.0~start: Failed to exec start script
14 verbose stack Error: angular2@0.0.0 start: `ng serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2@0.0.0
16 verbose cwd C:\ng\angular2-crudapp
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error angular2@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the angular2@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
